name: input-demo
on: 
    workflow_dispatch:
        inputs:
            dry-run :
                type: boolean
                description: "this is a test"
            target :
                type: string
                description: "this is a test target"
            tag :
              type: choice
              options:
                  - v1
                  - v2
jobs:
   input-demo:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              run: echo this is a ${{inputs.dry-run}}
   output-demo:
        runs-on: ubuntu-latest    
        steps:
            - name : build
              id: build
              run: echo "status=succes" >> $GITHUb_OUTPUT
        outputs:
            status-code: ${{steps.build.status}}
   test-output:
        runs-on: ubuntu-latest
        needs: output-demo
        steps:
            - name: test the output
              run : echo this is the output ${{needs.output-demo.status-code}}         

   
        
