name : address-book deployement 
on :
  push:
  workflow_call:   
concurrency: 
  group: first-group  
jobs :
    first-job :
        concurrency: 
          group:  job level 
        runs-on: ubuntu-22.04
        steps:
          - name: echo
            run : |
                echo this is the first message
                echo this is the second message
                echo this is the third message 

          - name: checkout code
            uses: actions/checkout@v4
          - run: 
                ls
          - name: update dependecies
            uses: actions/setup-node@v4
            with:
              node-version: '20.0'
          - run: npm ci
    second-job:
        runs-on: ubuntu-latest
        steps:
          - name: deploy to ec3
            run : |
              echo this is the second job running in sequence ${{github.second}}
              echo this is the second job running in sequence ${{github.second}}
              echo this is the second job running in sequence ${{github.second}}
    third-job:
        needs: second-job
        runs-on: ubuntu-latest
        steps:
            - name: deploy to ec3 third
              run : |
                echo this is the second job running in sequence ${{github.second}}
                echo this is the second job running in sequence ${{github.second}}
                echo this is the second job running in sequence ${{github.second}}
        
                 


